import { Dosis } from 'next/font/google';
import './globals.css';
import { ThemeProvider } from '@/components/theme-provider';
import { Navbar } from '@/components';
import Provider from '@/utils/Providers';
import { FiltersProvider } from '@/context/filtersContext';

const dosis = Dosis({ subsets: ['latin'] });

export const metadata = {
  title: 'Firucasa',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang='es' suppressHydrationWarning>
      <body className={dosis.className}>
        <FiltersProvider>
          <Provider>
            <ThemeProvider
              attribute='class'
              defaultTheme='light'
              enableSystem
              disableTransitionOnChange
            >
              <div className='min-h-screen'>
                <Navbar />
                <div className='container mx-auto'>{children}</div>
              </div>
            </ThemeProvider>
          </Provider>
        </FiltersProvider>
      </body>
    </html>
  );
}
